development:
  adapter: postgresql
  encoding: unicode
  database: lead_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
  host: localhost

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: lead_test
#   pool: 5
#   timeout: 5000
#   username: postgres
#   password: postgres


production:
  adapter: postgresql
  encoding: unicode
  database: lead_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
  host: localhost
